#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH="$HOME/.config/emacs/bin:$PATH"
export PATH="$HOME/repos/bin/pa:$PATH"
export PATH="$HOME/repos/bin/remint:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$HOME/.local/share/npm/bin:$PATH"
export PATH="$HOME/.config/cabal/bin:$PATH"
export PATH="/usr/local/texlive/2023/bin/universal-darwin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="$PATH:$HOME/.local/share/go/bin"

# unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"

# ~/ Clean-up:
export OPENAI_API_KEY=$(~/repos/bin/pa/pa show openai_apikey:mr.deangao@gmail.com)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$XDG_CONFIG_HOME/xdg"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}"/gem
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
export TAURI_PRIVATE_KEY="~/Documents/tauri/ttbl.key"
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
export CABAL_DIR="$XDG_DATA_HOME"/cabal


# == plugin config ==

RED="09"
GREEN="0a"
YELLOW="0b"
BLUE="0c"
MAGENTA="0d"
CYAN="0e"
WHITE="0f"
BLK="00" CHR="00" DIR="0e" EXE="0b" REG="00" HARDLINK="0e" LINK="0a" MISSING="00" ORPHAN="09" FIFO="0e" SOCK="00" OTHER="05"
DIR=$BLUE
EXE=$GREEN
SOCK=$MAGENTA
FIFO=$YELLOW
LINK=$CYAN
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$LINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
export NNN_READER=preview
export NNN_OPENER=nuke
export NNN_TRASH=2

export LSCOLORS="ExGxFxDxCxFxFxFxFxFxFx"

export FZF_DEFAULT_COMMAND="fd . -t f --hidden --follow --exclude .git --strip-cwd-prefix"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd . -t d --follow --strip-cwd-prefix"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:7,hl:11
--color=fg+:15,bg+:0,hl+:3
--color=info:14,prompt:12,pointer:11
--color=marker:4,spinner:#73d0ff,header:#d4bfff'

# Other program settings:
export LESS=-R
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export YSU_MODE=ALL
# export YSU_HARDCORE=1
export YSU_MESSAGE_FORMAT="use \"%alias\"."
export YSU_HARDCORE_MESSAGE_FORMAT="please."

export npm_config_prefix="$HOME/.local/share/npm"

export TTBL_COLOR="*"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1
