

# Carbon

spacing         = 0
padding         = 0
hide_ascii      = true
separator       = " "
key_color       = "Blue"
separator_color = "Yellow"

[palette]
type            = "Light"
glyph           = "  ● "
visible         = false

[bar]
glyph           = "●"
symbol_open     = '('
symbol_close    = ')'
visible         = true
hide_delimiters = true

[box]
title           = ""
border          = "Rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[custom_ascii]
color           = "Yellow"

[randomize]
key_color       = false
separator_color = false
pool            = "base"

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
